adding pdf conversion services and controllers
hmcts/finrem-document-generator-client pull request #91
Opened 2020-11-04 14:46 UTC by ocarleton

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/FR-1855

### Change description ###
adding endpoint and service to take in a word document and return a PDF document

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-11-10 16:40 UTC, shaunganley approved these changes

2020-11-10 16:40 UTC, shaunganley commented on src/main/java/uk/gov/hmcts/reform/finrem/documentgenerator/controller/DocumentConversionController.java
> +        log.info("document conversion service is null: {}", documentConversionService == null);
testing log

2020-11-10 16:40 UTC, shaunganley commented on src/main/java/uk/gov/hmcts/reform/finrem/documentgenerator/error/DocumentConversionException.java
> +
```suggestion
```

2020-11-10 16:40 UTC, shaunganley commented on src/main/java/uk/gov/hmcts/reform/finrem/documentgenerator/service/DocumentConversionService.java
> +
```suggestion
```

2020-11-10 17:34 UTC, jakub-kozlowski requested changes

2020-11-10 17:34 UTC, jakub-kozlowski commented on src/main/java/uk/gov/hmcts/reform/finrem/documentgenerator/controller/DocumentConversionController.java
> +    @ApiOperation(value = "Deletes document from the evidence management.", tags = {"Document Generation"})
Is it actually deleting document from Evidence Management? Looks like it's storing a PDF version

2020-11-10 17:34 UTC, jakub-kozlowski commented on src/main/java/uk/gov/hmcts/reform/finrem/documentgenerator/service/DocumentConversionService.java
> +        if (sourceDocument.getFileName().toLowerCase().endsWith(PDF)) {
I'm not convinced checking document extension is a valid way of checking the file type. We already have Apache Tika in DocGenService that can be leveraged for that purpose: https://github.com/hmcts/finrem-document-generator-client/blob/master/src/main/java/uk/gov/hmcts/reform/finrem/documentgenerator/config/DocumentGeneratorApplicationConfiguration.java#L12

2020-11-10 17:34 UTC, jakub-kozlowski commented on src/main/java/uk/gov/hmcts/reform/finrem/documentgenerator/service/DocumentConversionService.java
> +        return filename.split("\\.")[0] + ".pdf";
Better use something from `org.apache.commons.io.FilenameUtils` - the service has the library already included. This version would return eg. "order.pdf" for "order.contested.doc"

2020-11-11 16:38 UTC, jakub-kozlowski approved these changes

2020-11-25 16:19 UTC, merged